Project  documentation and configuration
BuildForSDG/voxnostra pull request #12
Opened 2020-05-02 04:37 UTC by tanerochris

## Description
Instruction to install and setup project in Setup section of the readme
The docs folder contains additional documentation on project structure.
All tests go in __tests__ 
Issues concerned.
#2  #5

2020-05-02 08:04 UTC, cliffordten submitted a review, later dismissed
This looks Ok, Project setup good

2020-05-03 13:56 UTC, dherve19 approved these changes

2020-05-03 13:58 UTC, dherve19 approved these changes
these are just setups so i am comfortable with the changes.

2020-05-03 14:15 UTC, dherve19 approved these changes
these are just setups so i am comfortable with the changes.

2020-05-03 14:18 UTC, dherve19 approved these changes
these are just setups so i am comfortable with the changes.

2020-05-03 14:19 UTC, dherve19 approved these changes

2020-05-03 14:19 UTC, dherve19 approved these changes

2020-05-03 14:21 UTC, dherve19 approved these changes

2020-05-03 14:21 UTC, dherve19 approved these changes

2020-05-03 14:22 UTC, dherve19 approved these changes

2020-05-03 14:22 UTC, dherve19 approved these changes

2020-05-03 14:23 UTC, dherve19 approved these changes

2020-05-03 14:24 UTC, dherve19 approved these changes

2020-05-03 14:25 UTC, dherve19 approved these changes

2020-05-03 14:26 UTC, dherve19 approved these changes

2020-05-03 14:27 UTC, dherve19 approved these changes

2020-05-03 14:28 UTC, dherve19 approved these changes

2020-05-03 14:29 UTC, dherve19 submitted a review, later dismissed

2020-05-03 14:52 UTC, cliffordten approved these changes

2020-05-03 14:54 UTC, cliffordten submitted a review, later dismissed

2020-05-03 15:33 UTC, dherve19 commented
i aprove this

2020-05-03 20:14 UTC, mernxl requested changes
Here are some small issues with the code

- [x] Its good we use either yarn or npm not both. Please delete one of the locks files. I see both package-lock.json and yarn.lock files. Yarn will be preferable please.
- [x] I could still see some typescript files in `/interfaces`

Apart from the small changes, all is good to go. Sorry for the delay.
Also kudos on the commit messages, convention commits are good choice for code story.

2020-05-03 20:14 UTC, mernxl commented on .gitignore
>  *.log
Add the following code to ignore IDE dependent files

```
# IDEA files
.idea

# Visual Studio Code
.vscode
```

2020-05-03 20:14 UTC, mernxl commented on .gitignore
> +npm-debug.log*
Remove this as its redundant
```
npm-debug.log*
yarn-debug.log*
yarn-error.log*
```
That is because we already have the `*.log` pattern

2020-05-03 23:17 UTC, tanerochris commented on .gitignore
> +npm-debug.log*
these updates have been done

2020-05-03 23:17 UTC, tanerochris commented on .gitignore
>  *.log
these updates have been done

2020-05-03 23:36 UTC, mernxl requested changes
One last, don't seem to find the yarn.lock file. I am guessing we are going with yarn. Last one, do a yarn install. commit the lock file.

My earlier review was for you to take out one of the two lock files.

2020-05-04 05:50 UTC, dherve19 approved these changes

2020-05-04 08:17 UTC, cliffordten approved these changes

2020-05-04 08:28 UTC, mernxl approved these changes
Ok, let's move on then.

Well, although there are some small minor issues. Like 

- I see `@types` dependencies which are used by typescript, and you said tsc support is removed
- I see some sort of _tsconfig.js file, configuration for typescript
- Package json still have typescript, ts-jest
- Also seen a `.prettierrc` file, with no integration with code base (Less files the better)
- cors is installed but not used
- Also, on `package.json` file, the `[project title]` part, i think its supposed to be replaced by the project title right?

2020-05-04 08:28 UTC, mernxl commented on package.json
>        "...": "..."
I think this entry isn't needed, 

```
  "...": "..."
```

2020-05-04 09:45 UTC, merged